# For details on these settings, visit https://github.com/narlock/UsefulItems
# Enable or disable features of this plugin
features:
  decrafter: true
  silktouch: true
  extendedcrafting: true
  enhanceditems: true

# Enable or disable certain blocks for decrafter feature
# Note: disabling decrafter in features.decrafter will disable all blocks!
decrafter-blocks:
  dispenser: true
  sandstone: true
  noteblock: true
  bed: true
  sticky_piston: true
  piston: true
  workbench: true
  furnace: true
  redstone_torch: true
  wooden_door: true
  lever: true
  stone_pressure_plate: true
  iron_door: true
  wooden_pressure_plate: true
  stone_button: true
  jukebox: true
  jack_o_lantern: true
  trapdoor: true
  fence: true
  sign_post: true
  wall_sign: true
  redstone_repeater_off: true
  redstone_repeater_on: true
  double_stone_slab: true
  brick_block: true
  gold_block: true
  iron_block: true
  diamond_block: true
  boat: true
  minecart: true

# Enable or disable certain blocks for silktouch feature
# Note: disabling silktouch in features.silktouch will disable all blocks!
silktouch-blocks:
  stone: true
  coal_ore: true
  glass: true
  lapis_ore: true
  cobweb: true
  fern: true
  bookshelf: true
  tilled_dirt: true
  diamond_ore: true
  redstone_ore: true
  snow_layer: true
  ice: true
  snow_block: true
  glowstone: true

# Enable or disable certain blocks for crafting
# Note: disabling extendedcrafting in features.extendedcrafting will disable all blocks!
extendedcrafting:
  cobweb: true
  doublestoneslab: true
  sponge: true
  mossycobble: true
  fire: true

# Configure enhanced items
enhanceditems:
  milkbucket:
    godmode-duration: 5  # seconds
  sugar:
    suffocation-duration: 3  # seconds (per sugar use)
  fireball:
    cooldown: 5  # seconds

# Other Enhancements
stairs-drop-stairs: true
boats-drop-boat: true
